// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjX25JILgG9BwPSbkBYlFOZk77EuIHxwE',
    appId: '1:805297169916:android:da72af0c7cb65df5ad3e79',
    messagingSenderId: '805297169916',
    projectId: 'iunity-app-69332',
    storageBucket: 'iunity-app-69332.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh_Lqo8OvJ4tPH0PUbUmsHyLRxy8qC3IY',
    appId: '1:805297169916:ios:f8f901bf506ab233ad3e79',
    messagingSenderId: '805297169916',
    projectId: 'iunity-app-69332',
    storageBucket: 'iunity-app-69332.firebasestorage.app',
    iosBundleId: 'com.iunity.app.iunity',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0rGADaotanqQ4IaudU7_VO430JVQ_4f4',
    appId: '1:805297169916:web:1aa9eee60a2f751cad3e79',
    messagingSenderId: '805297169916',
    projectId: 'iunity-app-69332',
    authDomain: 'iunity-app-69332.firebaseapp.com',
    storageBucket: 'iunity-app-69332.firebasestorage.app',
    measurementId: 'G-TEVBWWDR2M',
  );
}
